name: robustbenchpy311
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib_metadata=8.3.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - python_abi=3.11=2_cp311
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - autoattack==0.1
      - babel==2.17.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blobfile==3.0.0
      - blosc2==2.7.1
      - boto3==1.38.8
      - botocore==1.38.8
      - brainscore-brainio==1.1.0
      - brainscore-core==2.1.2
      - brainscore-vision==2.2.10
      - certifi==2024.7.4
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.3.2
      - clean-fid==0.1.35
      - click==8.1.8
      - clip-anytorch==2.6.0
      - cloudpickle==3.1.1
      - contourpy==1.2.1
      - coverage==7.6.12
      - coveralls==4.0.1
      - cox==0.1.post3
      - cycler==0.12.1
      - dask==2025.4.1
      - datasets==4.0.0
      - dctorch==0.1.2
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.8.1
      - entrypoints==0.4
      - eva-decord==0.6.1
      - fastjsonschema==2.21.1
      - filelock==3.15.4
      - fire==0.7.0
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.1.0
      - geotorch==0.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gputil==1.4.0
      - grpcio==1.65.5
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface==0.0.1
      - huggingface-hub==0.29.3
      - idna==3.7
      - imageio==2.37.0
      - importlib-metadata==4.13.0
      - iniconfig==2.0.0
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.12.0
      - jsonmerge==1.9.2
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - k-diffusion==0.1.1.post1
      - kiwisolver==1.4.5
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - latexcodec==3.0.0
      - lazy-loader==0.4
      - locket==1.0.0
      - lxml==5.4.0
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.8
      - netcdf4==1.7.2
      - networkx==3.3
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - numexpr==2.10.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - partd==1.4.2
      - peewee==3.18.1
      - perlin-noise==1.14
      - pillow==10.4.0
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - propcache==0.3.2
      - protobuf==5.27.3
      - psycopg2-binary==2.9.10
      - py-cpuinfo==9.0.0
      - py3nvml==0.2.7
      - pyarrow==21.0.0
      - pybtex==0.24.0
      - pycparser==2.22
      - pycryptodomex==3.22.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - pytest==8.3.4
      - pytest-mock==3.14.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - result-caching==0.1.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - robustbench==1.1
      - robustness==1.2.1.post2
      - rpds-py==0.24.0
      - s3transfer==0.12.0
      - safetensors==0.4.4
      - scikit-image==0.25.2
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.2
      - tables==3.10.1
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2025.3.30
      - timm==1.0.19
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - toolz==1.0.0
      - torch==2.4.0
      - torchdeq==0.1.0
      - torchdiffeq==0.2.4
      - torchsde==0.2.6
      - torchvision==0.19.0
      - tqdm==4.66.5
      - trampoline==0.1.2
      - transformers==4.50.2
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20241206
      - typing-inspection==0.4.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wandb==0.19.11
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.14
      - xarray==2022.3.0
      - xmltodict==0.13.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/tahereh/anaconda3/envs/robustbenchpy311
